# -*- coding: utf-8 -*-
"""data_ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kzffnu1TfPM30AFgvsFLR-ww7ByX3guq
"""

import pandas as pd
import os
from pathlib import Path

# Folder containing the 10 CSV files
DATA_FOLDER = "data/raw"

csv_files = list(Path(DATA_FOLDER).glob("*.csv"))

print(f"\nFound {len(csv_files)} CSV files\n")

dataset_summary = []

for file in csv_files:
    print("=" * 100)
    print(f"DATASET: {file.name}")
    print("=" * 100)

    try:
        # Load dataset
        df = pd.read_csv(file)

        # Shape
        print("\nShape:")
        print(df.shape)

        # Data Types
        print("\nData Types:")
        print(df.dtypes)

        # First 5 rows
        print("\nHead:")
        print(df.head())


        # Anomaly Checks

        anomalies = []

        # Missing values
        missing = df.isnull().sum()
        missing_cols = missing[missing > 0]

        if len(missing_cols) > 0:
            anomalies.append(
                f"Missing values found in {len(missing_cols)} columns"
            )

        # Duplicate rows
        duplicate_count = df.duplicated().sum()
        if duplicate_count > 0:
            anomalies.append(
                f"{duplicate_count} duplicate rows detected"
            )

        # Fully empty columns
        empty_cols = df.columns[df.isnull().all()].tolist()
        if empty_cols:
            anomalies.append(
                f"Completely empty columns: {empty_cols}"
            )

        # Columns with only one unique value
        constant_cols = [
            col for col in df.columns
            if df[col].nunique(dropna=False) <= 1
        ]

        if constant_cols:
            anomalies.append(
                f"Constant columns: {constant_cols}"
            )

        # Mixed data types (often imported as object)
        object_cols = df.select_dtypes(include="object").columns

        for col in object_cols:
            sample_types = df[col].dropna().map(type).nunique()
            if sample_types > 1:
                anomalies.append(
                    f"Mixed data types detected in '{col}'"
                )

        # Report anomalies
        print("\nAnomaly Check:")
        if anomalies:
            for a in anomalies:
                print(f"X {a}")
        else:
            print("No anomalies detected")

        dataset_summary.append({
            "Dataset": file.name,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
            "Missing Values": int(df.isnull().sum().sum()),
            "Duplicate Rows": int(duplicate_count)
        })

    except Exception as e:
        print(f"\nError reading {file.name}: {e}")


# Summary Table

print("\n\nDATASET SUMMARY")
print("=" * 100)

summary_df = pd.DataFrame(dataset_summary)

if not summary_df.empty:
    print(summary_df)
else:
    print("No datasets loaded.")