# -*- coding: utf-8 -*-
"""live_nav_fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYmAQo-FJiSb2D9mxdKKwa2vp1pY3TSB
"""

import time
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import requests


# MFAPI base URL
BASE_URL = "https://api.mfapi.in/mf"

# Output directory
OUTPUT_DIR = Path("data/processed")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Mutual fund schemes
SCHEMES = {
    "125497": "HDFC Top 100 Direct",
    "119551": "SBI Bluechip",
    "120503": "ICICI Bluechip",
    "118632": "Nippon Large Cap",
    "119092": "Axis Bluechip",
    "120841": "Kotak Bluechip",
}


def fetch_nav(scheme_code, scheme_name):
    """
    Fetch NAV data for a mutual fund scheme from MFAPI.
    """

    url = f"{BASE_URL}/{scheme_code}"

    print(f"\nFetching: {scheme_name}")
    print(f"Scheme Code: {scheme_code}")
    print(f"URL: {url}")

    try:
        response = requests.get(
            url,
            timeout=30,
            headers={
                "User-Agent": "Mozilla/5.0"
            }
        )

        # Raise an error for HTTP failures
        response.raise_for_status()

        # Parse JSON response
        data = response.json()

        # Extract metadata
        metadata = data.get("meta", {})

        # Extract NAV records
        nav_data = data.get("data", [])

        if not nav_data:
            print(f"No NAV data found for {scheme_code}")
            return None

        # Convert API records into a DataFrame
        df = pd.DataFrame(nav_data)

        # Add scheme information
        df.insert(0, "scheme_code", scheme_code)
        df.insert(1, "scheme_name", metadata.get(
            "scheme_name",
            scheme_name
        ))

        # Add timestamp showing when data was fetched
        df["fetched_at_utc"] = datetime.now(
            timezone.utc
        ).isoformat()

        # Convert NAV to numeric
        df["nav"] = pd.to_numeric(
            df["nav"],
            errors="coerce"
        )

        # Save individual raw CSV
        output_file = OUTPUT_DIR / f"{scheme_code}_nav_raw.csv"

        df.to_csv(
            output_file,
            index=False
        )

        print(f"Saved: {output_file}")
        print(f"Records: {len(df):,}")

        # Display latest NAV
        latest = df.iloc[0]

        print(
            f"Latest NAV: {latest['nav']} "
            f"on {latest['date']}"
        )

        return df

    except requests.exceptions.RequestException as error:
        print(
            f"Request failed for {scheme_code}: {error}"
        )
        return None

    except ValueError as error:
        print(
            f"JSON parsing failed for {scheme_code}: {error}"
        )
        return None


def main():

    all_data = []

    print("=" * 60)
    print("MUTUAL FUND NAV DATA INGESTION")
    print("=" * 60)

    # Fetch all schemes
    for scheme_code, scheme_name in SCHEMES.items():

        df = fetch_nav(
            scheme_code,
            scheme_name
        )

        if df is not None:
            all_data.append(df)

        # Small delay between API requests
        time.sleep(0.5)

    # Combine all schemes
    if all_data:

        combined_df = pd.concat(
            all_data,
            ignore_index=True
        )

        # Save combined raw CSV
        combined_file = OUTPUT_DIR / "mfapi_nav_raw.csv"

        combined_df.to_csv(
            combined_file,
            index=False
        )

        print("\n" + "=" * 60)
        print("INGESTION COMPLETE")
        print("=" * 60)

        print(f"Combined file: {combined_file}")
        print(f"Total records: {len(combined_df):,}")
        print(
            f"Schemes fetched: "
            f"{combined_df['scheme_code'].nunique()}"
        )

        print("\nRecords by scheme:")
        print(
            combined_df.groupby(
                ["scheme_code", "scheme_name"]
            ).size()
        )

    else:
        print("\nNo data was successfully fetched.")


if __name__ == "__main__":
    main()

import pandas as pd
from pathlib import Path


# 1. FILE PATHS

FUND_MASTER_FILE = Path("data/raw/01_fund_master.csv")
NAV_HISTORY_FILE = Path("data/raw/02_nav_history.csv")


# 2. LOAD DATA

fund_master = pd.read_csv(FUND_MASTER_FILE)
nav_history = pd.read_csv(NAV_HISTORY_FILE)


print("=" * 70)
print("DAY 1: FUND MASTER EXPLORATION & AMFI CODE VALIDATION")
print("=" * 70)


# ============================================================
# 3. DATASET INFORMATION

print("\nFund Master shape:")
print(fund_master.shape)

print("\nNAV History shape:")
print(nav_history.shape)


# 4. COLUMN NAMES

print("\nFund Master columns:")
print(fund_master.columns.tolist())

print("\nNAV History columns:")
print(nav_history.columns.tolist())


# 5. EXPLORE FUND HOUSES

print("\n" + "=" * 70)
print("1. UNIQUE FUND HOUSES")
print("=" * 70)

fund_houses = (
    fund_master["fund_house"]
    .dropna()
    .unique()
)

print(fund_houses)

print("\nNumber of unique fund houses:")
print(fund_master["fund_house"].nunique())


# 6. EXPLORE CATEGORIES

print("\n" + "=" * 70)
print("2. UNIQUE CATEGORIES")
print("=" * 70)

categories = (
    fund_master["category"]
    .dropna()
    .unique()
)

print(categories)

print("\nNumber of unique categories:")
print(fund_master["category"].nunique())


# 7. EXPLORE SUB-CATEGORIES

print("\n" + "=" * 70)
print("3. UNIQUE SUB-CATEGORIES")
print("=" * 70)

sub_categories = (
    fund_master["sub_category"]
    .dropna()
    .unique()
)

print(sub_categories)

print("\nNumber of unique sub-categories:")
print(fund_master["sub_category"].nunique())


# 8. EXPLORE RISK CATEGORIES

print("\n" + "=" * 70)
print("4. UNIQUE RISK CATEGORIES")
print("=" * 70)

risk_categories = (
    fund_master["risk_category"]
    .dropna()
    .unique()
)

print(risk_categories)

print("\nNumber of unique risk categories:")
print(fund_master["risk_category"].nunique())


# 9. AMFI SCHEME CODE EXPLORATION

print("\n" + "=" * 70)
print("5. AMFI SCHEME CODE STRUCTURE")
print("=" * 70)

print("\nSample AMFI codes:")
print(
    fund_master[
        ["amfi_code", "scheme_name", "fund_house"]
    ].head(10)
)

print("\nNumber of unique AMFI codes:")
print(
    fund_master["amfi_code"].nunique()
)

print(
    """
AMFI scheme codes are numeric identifiers used to identify
individual mutual fund schemes.

For example:

119551 = SBI Bluechip Fund - Regular Plan - Growth
119552 = SBI Bluechip Fund - Direct Plan - Growth

The AMFI code is an identifier. It should not be interpreted
as a code where individual digits represent the fund house,
category, or risk level.

The AMFI code is used to connect fund master information
with NAV history data.
"""
)


# 10. VALIDATE AMFI CODES

print("\n" + "=" * 70)
print("6. AMFI CODE VALIDATION")
print("=" * 70)


# Convert codes to strings to avoid type mismatches
fund_codes = set(
    fund_master["amfi_code"]
    .dropna()
    .astype(str)
    .str.strip()
)

nav_codes = set(
    nav_history["amfi_code"]
    .dropna()
    .astype(str)
    .str.strip()
)


# Codes in fund_master but NOT in nav_history
missing_codes = sorted(
    fund_codes - nav_codes
)


# Codes in nav_history but NOT in fund_master
extra_codes = sorted(
    nav_codes - fund_codes
)


# Codes present in both datasets
matching_codes = sorted(
    fund_codes & nav_codes
)


print(
    "Unique AMFI codes in fund_master:",
    len(fund_codes)
)

print(
    "Unique AMFI codes in nav_history:",
    len(nav_codes)
)

print(
    "Matching AMFI codes:",
    len(matching_codes)
)

print(
    "Missing from nav_history:",
    len(missing_codes)
)

print(
    "Extra codes in nav_history:",
    len(extra_codes)
)


# 11. DISPLAY MISSING CODES

if missing_codes:

    print("\nAMFI codes present in fund_master")
    print("but missing from nav_history:")

    for code in missing_codes:
        print(code)

else:

    print(
        "\nPASS: Every AMFI code in fund_master "
        "exists in nav_history."
    )


# 12. DISPLAY EXTRA CODES

if extra_codes:

    print("\nAMFI codes present in nav_history")
    print("but missing from fund_master:")

    for code in extra_codes:
        print(code)

else:

    print(
        "PASS: No extra AMFI codes found in nav_history."
    )


# 13. DUPLICATE CHECK

print("\n" + "=" * 70)
print("7. DUPLICATE AMFI CODE CHECK")
print("=" * 70)

fund_duplicates = (
    fund_master["amfi_code"]
    .duplicated()
    .sum()
)

nav_duplicates = (
    nav_history["amfi_code"]
    .duplicated()
    .sum()
)

print(
    "Duplicate AMFI code rows in fund_master:",
    fund_duplicates
)

print(
    "Duplicate AMFI code rows in nav_history:",
    nav_duplicates
)


# 14. MISSING VALUE CHECK

print("\n" + "=" * 70)
print("8. MISSING VALUE CHECK")
print("=" * 70)

print("\nFund Master missing values:")

print(
    fund_master.isna().sum()
)

print("\nNAV History missing values:")

print(
    nav_history.isna().sum()
)



# 15. FINAL DATA QUALITY SUMMARY

print("\n" + "=" * 70)
print("9. DATA QUALITY SUMMARY")
print("=" * 70)


if len(missing_codes) == 0:
    validation_status = "PASS"
else:
    validation_status = "FAIL"


print(f"""
AMFI Code Validation: {validation_status}

Fund Master records: {len(fund_master):,}
NAV History records: {len(nav_history):,}

Unique fund houses: {fund_master["fund_house"].nunique()}
Unique categories: {fund_master["category"].nunique()}
Unique sub-categories: {fund_master["sub_category"].nunique()}
Unique risk categories: {fund_master["risk_category"].nunique()}

Unique AMFI codes in fund_master: {len(fund_codes):,}
Unique AMFI codes in nav_history: {len(nav_codes):,}

Matching AMFI codes: {len(matching_codes):,}
Missing AMFI codes: {len(missing_codes):,}
Extra AMFI codes: {len(extra_codes):,}

Duplicate codes in fund_master: {fund_duplicates:,}
Duplicate codes in nav_history: {nav_duplicates:,}
""")